error_reading_dataframe = ArgumentError("\"/home/users/nticea/code/QuasiperiodicSuperconductivity/data_collection/phase_diagram/data/17L_ΦQ_LGE_2023-07-11_21:35:39.csv\" is not a valid file or doesn't exist")
Finding Tc using LGE
s-wave configuration
λ = 0.1549315858339646
I've returned
s-wave configuration
λ = 0.19131775948716387
error_reading_dataframe = ArgumentError("\"/home/users/nticea/code/QuasiperiodicSuperconductivity/data_collection/phase_diagram/data/17L_ΦQ_LGE_2023-07-16_17:11:33.csv\" is not a valid file or doesn't exist")
Already computed!
